### PR TITLE
Added e2e tests for allowPrivilegeEscalation psp policy

### LINKED ISSUE #11: Implement e2e tests
Right now the policy doesn't have e2e tests.

### PR DESCRIPTION
**Pull request by 0xquark**
Signed-off-by: Karanjot Singh <drquark@duck.com>

## Description
This is my first time working on e2e tests for a policy, and I would appreciate it if you could take a look and let me know if there are any changes or improvements you would like me to make.

I have included a brief description of the tests, which I have taken from the test_data

Fix #11 

## Test
The first test, "reject pod with allowPrivilegeEscalation disabled," checks whether the policy will reject a pod request where the allowPrivilegeEscalation attribute is set to false. The output of the policy is checked for the string "allowed=false" and the presence of the string "allowPrivilegeEscalation=false". If both of these conditions are met, the test is considered to have passed.
The second test, "accept pod without security context," checks whether the policy will accept a pod request that does not have a security context defined. The output of the policy is checked for the string "allowed=true".
The third test, "reject pod with container with security context and allowPrivilegeEscalation set to true," checks whether the policy will reject a pod request where the security context of a container within the pod is set with allowPrivilegeEscalation=true. The output of the policy is checked for the string "allowed=false" and the presence of the string "allowPrivilegeEscalation=true".
The fourth test, "reject pod with init container with security context and allowPrivilegeEscalation set to true," is similar to the third test, but checks for the same conditions in an init container within the pod.

### CODE REVIEW

**Review by flavio — APPROVED** [review]
LGTM, thanks for your contribution.

I've just triggered the execution of the unit tests. I'll merge the PR if everything is green

**Comment by viccuad** [comment]
Many thanks, merging!

**Review by viccuad — COMMENTED** [review]
LGTM

**Comment by 0xquark** [comment]
Thank you  🚀

**Comment by flavio** [comment]
I just realized we do not run e2e tests as part of the PR actions. They are run only when doing the release step, which happens as soon as something is merged on `main` or a new tag is released.

I think we should change that, but this is not related with this PR

**Comment by 0xquark** [comment]
Ohk! Let me know if you run into issues while running the tests

**Comment by viccuad** [comment]
@0xquark I think there may be indeed some mistakes in the e2e tests.

First, I needed to change `e2e.bats`,  the `kwctl run` commands should use the `annotated-policy.wasm` (so, `run kwctl run annotated-policy.wasm` for example). That `annotated-policy.wasm` file is the compiled wasm module, plus annotations from `metadata.yml`, that inform `kwctl` and `policy-server` on how to run the policy (see for example [this page in docs](https://docs.kubewarden.io/distributing-policies#annotating-the-policy), in adittion to others).  


After doing that, tests are failing locally for me:

```console
$ make e2e-tests
bats e2e.bats
e2e.bats
 ✗ reject pod with allowPrivilegeEscalation disabled
   (in test file e2e.bats, line 11)
     `[ $(expr "$output" : '.*allowed.*false') -ne 0 ]' failed
   output = {"uid":"1299d386-525b-4032-98ae-1949f69f9cfc","allowed":true,"auditAnnotations":null,"warnings":null}
 ✓ accept pod without security context
 ✗ reject pod with container with security context and allowPrivilegeEscalation set to true
   (in test file e2e.bats, line 35)
     `[ $(expr "$output" : ".*allowPrivilegeEscalation.*true.*") -ne 0 ]' failed
   output = {"uid":"1299d386-525b-4032-98ae-1949f69f9cfc","allowed":false,"status":{"message":"one of the containers has privilege escalation enabled"},"auditAnnotations":null,"warnings":null}
 ✗ reject pod with init container with security context and allowPrivilegeEscalation set to true
   (in test file e2e.bats, line 47)
     `[ $(expr "$output" : ".*allowPrivilegeEscalation.*true.*") -ne 0 ]' failed
   output = {"uid":"1299d386-525b-4032-98ae-1949f69f9cfc","allowed":false,"status":{"message":"one of the init containers has privilege escalation enabled"},"auditAnnotations":null,"warnings":null}

4 tests, 3 failures

make: *** [Makefile:20: e2e-tests] Error 1
```

**Comment by 0xquark** [comment]
@viccuad I am running into issues while trying to run the test! 
`failed to select a version for the requirement `kubewarden-policy-sdk = "^0.8.7"`
candidate versions found which didn't match: 0.5.1, 0.5.0, 0.4.2, ...`
I've made PR #42 to discuss this!

**Pull request merged**
